# Generated by Django 6.0 on 2025-12-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school_auth', '0002_schooladmin_groupcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schooladmin',
            name='groupCategory',
            field=models.OneToOneField(default='Principal', on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
