# Generated by Django 6.0 on 2025-12-16 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('school_auth', '0004_alter_schooladmin_groupcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmin',
            name='fullName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schooladmin',
            name='groupCategory',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
    ]
