# Generated by Django 6.0 on 2025-12-17 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_auth', '0005_schooladmin_fullname_alter_schooladmin_groupcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='externalAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AdminEmail', models.EmailField(max_length=254)),
                ('AdminPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
