# Generated by Django 6.0 on 2025-12-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_auth', '0006_externalaccess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='externalaccess',
            old_name='AdminPassword',
            new_name='admin_password',
        ),
        migrations.RemoveField(
            model_name='externalaccess',
            name='AdminEmail',
        ),
        migrations.AddField(
            model_name='externalaccess',
            name='admin_email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
