# Generated by Django 6.0 on 2025-12-18 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_auth', '0007_rename_adminpassword_externalaccess_admin_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalaccess',
            name='admin_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
